[shell]
    program= "C:\\Windows\\System32\\wsl.exe ~"
    args = ["-d Ubuntu"]
  
[env]
    TERM = "xterm-256color"
		
[window]
    decorations = "full"
		
[font.normal]
    family = "0xProto Nerd Font Mono"
    style = "Regular"
